services:
  obsidian:
    image: ghcr.io/sytone/obsidian-remote:latest
    container_name: obsidian
    restart: unless-stopped

    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Warsaw"
      CUSTOM_PORT: "8080"

    volumes:
      - /srv/obsidian/vaults:/vaults:Z
      - /srv/obsidian/config:/config:Z

    networks:
      - server

networks:
  server:
    external: true