services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped

    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.home.arpa

    volumes:
      - ./config:/app/config:Z
      - ./config/images:/app/public/images:ro

    networks:
      - server

networks:
  server:
    external: true
