services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

    security_opt:
      - label=disable

    networks:
      - server

    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /mnt/movies:/media:ro
      - type: bind
        source: /mnt/music
        target: /music
        read_only: false
        bind:
          propagation: rshared

networks:
  server:
    external: true
    name: server

volumes:
  jellyfin-config:
  jellyfin-cache: